server:
  port: 5050

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <Client-ID>
            client-secret: <Client-Secret>

          facebook:
            client-id: <Client-ID>
            client-secret: <Client-Secret>

          github:
            client-id: <Client-ID>
            client-secret: <Client-Secret>
